### ISSUE TITLE
添加新的 API

### ISSUE THREAD

**Issue by nickChenyx** [cheezone/ZhihuVAPI#1]
**个人关注类**

- 获取个人关注的话题列表
- 获取个人关注的专栏列表
- 获取个人关注的问题列表
- 获取个人关注的收藏夹列表

这些接口可以和已有的 API 整合使用，建议添加(我不会说是我想用 = =||)

**Comment by cheezone** [comment]
你安装一下最新版:`pip install -U ZhihuVAPI`吧。

你说的功能在里面已经有了，但是调用的时候会有 Bug，使用我更新了一下，你可以这么调用：
```Python
import ZhihuVAPI as zhihu
self = zhihu.self
for v in self.following_columns():
    dosomethings
```
同理，self.following_collections、self.following_topics、 self.following_questions 你也可以按这种方式调用，这是 People 类的属性。你可以在 People.py看到对应的代码。
