### ISSUE TITLE
你好，我想学习一下这个，但是有个地方不太明白

### ISSUE THREAD

**Issue by ZhangSanMo** [cheezone/ZhihuVAPI#2]
\# 开始构造
        if zhihu.test(self, 'id', id):  # 传入 ID 的情况
            self.init(id=id)

这里的init是什么，它不是__init__()我也没看到它的实现。

谢谢您的解答

**Comment by cheezone** [comment]
有啊...就在`__init__`的下面
![](https://i.loli.net/2018/08/26/5b823dc2af632.png)

**Comment by ZhangSanMo** [comment]
晓得了，谢谢！
